#!/bin/sh

# Manually set up clock; skip sync_role
set.site 0 SYS:CLK:FPMUX FPCLK
set.site 1 CLK=external
set.site 1 CLK:DX=d0
set.site 1 CLK:SENSE=rising
set.site 1 CLKDIV=1

# For other combinations try 'set.site 0 sync_role help'
# configure dig encoder
set.site 2 phaseA_en 1
set.site 2 zsel 3
set.site 2 Zcount_en 1

set.site 0 SIG:EVENT_SRC:3 MOD
set.site 1 rtm_translen=8192
set.site 1 trg=1,1,1
set.site 1 rgm=3,3,1

echo STREAM_OPTS= >> /etc/sysconfig/acq400_streamd.conf
get.site 1 clk >> /mnt/clk_config.log

