#!/bin/sh
# custom_hyl_early .. do this before IOC

# configure soft trigger on site 1 - typical default
set.site 1 trg=1,1,1

# Configure active channels on QEN Biscuit
rm -f /etc/acq400/2/active_chan
rm -f /etc/acq400/2/data32
echo 0 > /etc/acq400/2/data32 
echo 4 > /etc/acq400/2/active_chan
echo 4 > /etc/acq400/2/NCHAN

# Enable SPAD to include uSecond counter in the data
set.site 0 spad 1,2,0 
set.site 0 spad1_us 1,2,1


# set sites in aggregator set
run0 1,2

# configure transient channel data server at ports 53000+CH
make-ch-server



# nobble TRG.d0
cd /dev/gpio/TRG
mv d0 _d0
echo 0 > d0

# awk this .. it's not going to move, so we hard-code for now:
# /dev/gpio/TRG/d0 -> /sys/class/gpio/gpio448/value
# acq1001_507> ls -l /sys/class/gpio/ | grep 448
# gpio448 -> ../../devices/soc0/amba/e000a000.gpio/gpiochip0/gpio/gpio448
# acq1001_507> ls -l /sys/class/gpio/gpiochip* | grep e000a000.gpio
# /sys/class/gpio/gpiochip394 -> ../../devices/soc0/amba/e000a000.gpio/gpio/gpiochip394

echo 448 > /sys/class/gpio/unexport
echo $((448-394)) >/dev/gpio/TRG/d0_offset


